import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/utils/provider/queryProvider";
import FontProvider from "@/utils/provider/fontProvider";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "EXL",
  description: "Generated by LWS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader color="#E30613" />
        <QueryProvider>
          <FontProvider>{children}</FontProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
